development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URL"] %>
      options:
        server_api:
          version: "1"

test:
  clients:
    default:
      uri: <%= ENV["MONGODB_URL"] %>
      options:
        server_api:
          version: "1"

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URL"] %>
      options:
        server_api:
          version: "1"
