development:
  clients:
    default:
      uri: <%= ENV['MONGO_DB_URL'] %>
  options:
    use_activesupport_time_zone: true

test:
  clients:
    default:
      uri: <%= ENV['MONGO_DB_URL_TEST'] %>
  options:
    use_activesupport_time_zone: true

production:
  clients:
    default:
      uri: <%= ENV['MONGO_DB_URL'] %>
  options:
    use_activesupport_time_zone: true
